language: go
go:
- 1.x
- '1.8'
- 1.10.x
- master
matrix:
  allow_failures:
  - go: master
  fast_finish: true
install:
- go test
env:
  matrix:
    secure: Wj+28Zah4peDqbTrs7jRK8Q3uexnTnL8mEZPiFpCO5dlgXmtcxEzUH0h4sfvWVJvAOgJLKGnDC98RK58IuCVrwJWNzYKzmxC06MnXj0gumbWbPgJ5voW2k8ooIqozQXdfYw76EUKqM9E5H9Ynomva2sTEszL8QteHpBbNE0nYCSXlZmi9XetfJKSbqmAouX7mcS+lEnGpNdEeiYDOdLrkSMBoE763dfZHKHyqG11Gk7dlsnuqbqpzWz/sd+fS2y3yZx/7uJuphEFLmDwJDo23H2qXLFTYDK7Uhru4BFYix4nXHaHFHZayd2yNjpZa5p3y5PEkXKWBVLmV7y6lQe2vPeNuGorn3NqbQioSv6mEBHENvHNMbEz6Ts+FQrj13OEdjTQVj7xGqSqgCwahSOVuWrjKy5Krdx8gheF+1s5fPQAu6aUzVNxmTmrSyf/9q88cUEStYigkCwFLzYw10+ud7g8h2VTbe9+wzcFuq03lk/7oRvJ0bwH7rxVvpRjyL9Suh6PKVc0oLLBnt8HPolRvSk9TD6OM0XCTPVON57S0NC2TjvHlwThkfsdyCkrdTtw94V1ok57U3KbIncrXSmFYoso4sZVf44clYNVGMDfgyGvPU8k2IjpxBYczyPqJ7oHi5AkRrs5my0an2VYc2k7ehmuLn9Zzvds/vBXv9fcZ8A=
